### ISSUE TITLE
[BUG] google.api_core.exceptions.FailedPrecondition on createEntry

### ISSUE THREAD

**Issue by mesmacosta** [GoogleCloudPlatform/datacatalog-connectors#37]
**What happened**:

- Received the following error when running the hive connector:

```
Traceback (most recent call last):
  File "/opt/connectors/datacatalog-connectors-hive/env/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/opt/connectors/datacatalog-connectors-hive/env/lib/python3.7/site-packages/grpc/_channel.py", line 923, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/opt/connectors/datacatalog-connectors-hive/env/lib/python3.7/site-packages/grpc/_channel.py", line 826, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.FAILED_PRECONDITION
        details = "Precondition check failed."
        debug_error_string = "{"created":"@1608139786.728317411","description":"Error received from peer ipv4:108.177.111.95:443","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Precondition check failed.","grpc_status":9}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/connectors/datacatalog-connectors-hive/env/bin/google-datacatalog-hive-connector", line 8, in <module>
    sys.exit(main())
  File "/opt/connectors/datacatalog-connectors-hive/env/lib/python3.7/site-packages/google/datacatalog_connectors/hive/datacatalog_cli.py", line 87, in main
    Hive2DatacatalogCli().run(argv[1:] if len(argv) > 0 else argv)
  File "/opt/connectors/datacatalog-connectors-hive/env/lib/python3.7/site-packages/google/datacatalog_connectors/hive/datacatalog_cli.py", line 46, in run
    enable_monitoring=args.enable_monitoring).run()
  File "/opt/connectors/datacatalog-connectors-hive/env/lib/python3.7/site-packages/google/datacatalog_connectors/hive/sync/datacatalog_synchronizer.py", line 126, in run
    self.__ingest_created_or_updated(prepared_entries)
  File "/opt/connectors/datacatalog-connectors-hive/env/lib/python3.7/site-packages/google/datacatalog_connectors/hive/sync/datacatalog_synchronizer.py", line 141, in __ingest_created_or_updated
    ingestor.ingest_metadata([database_entry, *table_related_entries])
  File "/opt/connectors/datacatalog-connectors-hive/env/lib/python3.7/site-packages/google/datacatalog_connectors/commons/ingest/datacatalog_metadata_ingestor.py", line 65, in ingest_metadata
    self.__ingest_entries(entry_group_name, assembled_entries_data, config)
  File "/opt/connectors/datacatalog-connectors-hive/env/lib/python3.7/site-packages/google/datacatalog_connectors/commons/ingest/datacatalog_metadata_ingestor.py", line 95, in __ingest_entries
    entry_group_name, entry_id, new_entry)
  File "/opt/connectors/datacatalog-connectors-hive/env/lib/python3.7/site-packages/google/datacatalog_connectors/commons/datacatalog_facade.py", line 104, in upsert_entry
    entry=entry)
  File "/opt/connectors/datacatalog-connectors-hive/env/lib/python3.7/site-packages/google/datacatalog_connectors/commons/datacatalog_facade.py", line 51, in create_entry
    entry=entry)
  File "/opt/connectors/datacatalog-connectors-hive/env/lib/python3.7/site-packages/google/cloud/datacatalog_v1beta1/services/data_catalog/client.py", line 983, in create_entry
    response = rpc(request, retry=retry, timeout=timeout, metadata=metadata,)
  File "/opt/connectors/datacatalog-connectors-hive/env/lib/python3.7/site-packages/google/api_core/gapic_v1/method.py", line 145, in __call__
    return wrapped_func(*args, **kwargs)
  File "/opt/connectors/datacatalog-connectors-hive/env/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.FailedPrecondition: 400 Precondition check failed.
```
- This was also reported from users that use the commons connector directly.

**What you expected to happen**:
This Entry should be ingested or skipped, but should not break the connector execution.

**How to reproduce it (as minimally and precisely as possible)**:
I've noticed this happen when there are a lot of entries 10.000+ in the same entry group, then you clean up a large amount of entries in the same entry group 2.000+. And run the connector again.

**Anything else we need to know?**:
No

**Comment by mesmacosta** [comment]
There is also an open issue related to this: https://issuetracker.google.com/issues/170052119.
