### ISSUE TITLE
[BUG] MySQL connector

### ISSUE THREAD

**Issue by shirleycohen** [GoogleCloudPlatform/datacatalog-connectors#52]
**What happened**:

==============Prepare metadata===============
INFO:root:
--> database: Sakila
INFO:root:
23 tables ready to be ingested...
Traceback (most recent call last):
  File "/opt/conda/bin/google-datacatalog-mysql-connector", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/google/datacatalog_connectors/mysql_/datacatalog_cli.py", line 101, in main
    MySQL2DatacatalogCli().run(argv[1:] if len(argv) > 0 else argv)
  File "/opt/conda/lib/python3.7/site-packages/google/datacatalog_connectors/rdbms/datacatalog_cli.py", line 58, in run
    config=self._get_config()).run()
  File "/opt/conda/lib/python3.7/site-packages/google/datacatalog_connectors/rdbms/sync/datacatalog_synchronizer.py", line 101, in run
    metadata, tag_templates_dict)
  File "/opt/conda/lib/python3.7/site-packages/google/datacatalog_connectors/rdbms/sync/datacatalog_synchronizer.py", line 122, in __prepare_datacatalog_entries
    metadata)
  File "/opt/conda/lib/python3.7/site-packages/google/datacatalog_connectors/rdbms/prepare/assembled_entry_factory.py", line 50, in make_entries
    table_container['tables'], table_container['name'])
  File "/opt/conda/lib/python3.7/site-packages/google/datacatalog_connectors/rdbms/prepare/assembled_entry_factory.py", line 78, in __make_entry_for_tables
    make_entry_for_tables(table_dict, table_container_name)
  File "/opt/conda/lib/python3.7/site-packages/google/datacatalog_connectors/rdbms/prepare/datacatalog_entry_factory.py", line 149, in make_entry_for_tables
    column['type'])))
  File "/opt/conda/lib/python3.7/site-packages/google/datacatalog_connectors/rdbms/prepare/datacatalog_entry_factory.py", line 173, in __format_entry_column_type
    formatted_name = source_name.replace('&', '_')
TypeError: a bytes-like object is required, not 'str'

**How to reproduce it (as minimally and precisely as possible)**:

pip install google-datacatalog-mysql-connector

google-datacatalog-mysql-connector \
--datacatalog-project-id=$MYSQL2DC_DATACATALOG_PROJECT_ID \
--datacatalog-location-id=$MYSQL2DC_DATACATALOG_LOCATION_ID \
--mysql-host=$MYSQL2DC_MYSQL_SERVER \
--mysql-user=$MYSQL2DC_MYSQL_USERNAME \
--mysql-pass=$MYSQL2DC_MYSQL_PASSWORD \
--mysql-database=$MYSQL2DC_MYSQL_DATABASE

**Comment by mesmacosta** [comment]
Thanks for opening this @shirleycohen, I will check it out.

**Comment by mesmacosta** [comment]
Hi @shirleycohen, I just ran the `google-datacatalog-mysql-connector` on a fresh MySQL 5.7 instance successfully.

Could you give me more details on the database server you are running?

Looking at the stack trace, it breaks when parsing a table `column_type`. Maybe something related to database version, collation, encoding...

So I am able to reproduce the error, thanks!
